// Integration tests for the Main10 HEVC decode path (PR2 acceptance gate A2.2).
//
// The round-trip test reads a vendored P010LE fixture generated by
// `examples/gen_main10_fixture.rs` and decodes it via
// `HevcSwMain10FfmpegDecoder`. It is `#[ignore]`d until the fixture is
// generated on real hardware (see `tests/fixtures/README.md`).
//
// The `decoder_constructs` test is unconditional (no HW required).

#[cfg(feature = "ffmpeg-decode-hevc-sw-main10-any")]
mod sw_main10 {
    use prdt_media_ffmpeg::hevc_sw_main10_decoder::{
        HevcSwMain10FfmpegDecoder, HevcSwMain10FfmpegDecoderConfig,
    };
    // HevcDecoderBackend10 must be in scope for backend_name() / drain_frame().
    use prdt_media_ffmpeg::HevcDecoderBackend10;

    /// Verifies the SW Main10 decoder can be constructed without HW.
    /// Fails only if libavcodec lacks the `hevc` codec (should never happen
    /// in the dev container or ubuntu-latest runners).
    #[test]
    fn decoder_constructs() {
        let cfg = HevcSwMain10FfmpegDecoderConfig::default();
        let dec = HevcSwMain10FfmpegDecoder::new(cfg)
            .expect("hevc SW Main10 decoder must be present in dev-container libavcodec");
        assert_eq!(dec.backend_name(), "ffmpeg-sw-hevc-main10");
    }

    /// Round-trip test: decode the vendored Main10 fixture and assert:
    ///   - `Nv12Frame16` plane dims match (320x240).
    ///   - `hdr10` sidecar is `Some(_)` (SEI present in fixture).
    ///   - First Y sample's high 10 bits fall in legal limited-range [64, 940].
    ///
    /// Ignored until `tests/fixtures/main10_sample.hevc` is generated.
    /// See `tests/fixtures/README.md` for the fixture-generation procedure.
    #[test]
    #[ignore = "requires main10_sample.hevc fixture; see tests/fixtures/README.md"]
    fn round_trip_sw_main10_fixture() {
        let fixture = include_bytes!("fixtures/main10_sample.hevc");
        assert!(
            !fixture.is_empty(),
            "fixture is a placeholder — regenerate per tests/fixtures/README.md"
        );

        let cfg = HevcSwMain10FfmpegDecoderConfig {
            width: 320,
            height: 240,
        };
        let mut dec =
            HevcSwMain10FfmpegDecoder::new(cfg).expect("hevc SW Main10 decoder construction");

        dec.feed_packet(fixture, 0).expect("feed Main10 fixture");

        let frame = dec
            .drain_frame()
            .expect("drain after feeding IDR")
            .expect("expected one decoded frame from IDR fixture");

        // Plane dimensions.
        assert_eq!(frame.width, 320, "decoded width");
        assert_eq!(frame.height, 240, "decoded height");
        assert!(
            frame.stride_y as usize >= 320,
            "Y stride must cover width in u16 elements"
        );
        assert!(
            frame.stride_uv as usize >= 320,
            "UV stride must cover width in u16 elements"
        );

        // HDR10 sidecar must be present (fixture is encoded with BT.2020 PQ SEI).
        assert!(
            frame.hdr10.is_some(),
            "expected HDR10 sidecar in Main10 fixture — missing mastering_display SEI"
        );

        // First Y sample must be in legal limited-range for 10-bit [64, 940].
        let first_y = frame.y[0];
        // P010LE stores valid 10 bits in the HIGH 10 bits of each u16.
        let y10 = first_y >> 6;
        assert!(
            (64..=940).contains(&y10),
            "first Y sample {y10} (raw u16 {first_y:#06x}) outside legal Main10 limited-range [64, 940]"
        );
    }
}
